name: Build and Upload Flutter RPM on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Adaptez cette commande selon la plateforme ciblée (web, linux, etc.)
      - name: Build Flutter (web)
        run: flutter build web --release

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Prepare package directory
        run: |
          mkdir -p package/usr/share/my_flutter_app
          cp -r build/web/* package/usr/share/my_flutter_app/

      - name: Create RPM package
        run: |
          fpm -s dir -t rpm -n my_flutter_app -v "${{ github.event.release.tag_name }}" -C package usr/share/my_flutter_app

      - name: Find RPM file
        id: find_rpm
        run: echo "::set-output name=rpm_file::$(ls *.rpm)"

      - name: Upload RPM to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_rpm.outputs.rpm_file }}
          asset_name: ${{ steps.find_rpm.outputs.rpm_file }}
          asset_content_type: application/x-rpm
