name: AppImage Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - ARCH: x64
            RUNS_ON: ubuntu-24.04
            APPIMAGE_BUILDER_IMAGE: appimagecrafters/appimage-builder:1.1.0
          - ARCH: arm64
            RUNS_ON: ubuntu-24.04-arm
            APPIMAGE_BUILDER_IMAGE: appimagecrafters/appimage-builder:1.1.0-arm64

    name: Build ${{ matrix.ARCH }}
    runs-on: ${{ matrix.RUNS_ON }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: 3.27.4

    - run: flutter config --enable-linux-desktop

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev \
        libfuse2 keybinder-3.0 squashfs-tools python3-pip \
        liblzma-dev libstdc++-12-dev

    - name: Build flutter app
      run: flutter build linux --target-platform linux-${{ matrix.ARCH }} --release

    - name: Patch AppImageBuilder for architecture
      run: |
        sed -i "s/x64/${{ matrix.ARCH }}/g" ./AppImageBuilder.yml
        sed -i "s/arch: x86_64/arch: ${{ matrix.ARCH }}/" ./AppImageBuilder.yml

    - name: Build AppImage
      uses: docker://${{ matrix.APPIMAGE_BUILDER_IMAGE }}
      with:
        entrypoint: appimage-builder
        args: --recipe ./AppImageBuilder.yml --skip-test

    - name: Rename AppImage with arch
      run: |
        mv *.AppImage fileweightloss-${{ matrix.ARCH }}.AppImage || true
        mv *.AppImage.zsync fileweightloss-${{ matrix.ARCH }}.AppImage.zsync || true

    - name: Upload Artifact
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: '2.0.0'
        prerelease: false
        draft: true
        files: |
          ./fileweightloss-${{ matrix.ARCH }}.AppImage
          ./fileweightloss-${{ matrix.ARCH }}.AppImage.zsync
        repo_token: ${{ secrets.GITHUB_TOKEN }}
