name: AppImage Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - ARCH: x86_64
            RUNS_ON: ubuntu-24.04
          - ARCH: armhf
            RUNS_ON: ubuntu-24.04-arm

    name: Build ${{ matrix.ARCH }}
    
    runs-on: ${{ matrix.RUNS_ON }}

    env:
      ARCH: ${{ matrix.ARCH }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: 3.27.4
    - run: flutter --version
    - run: flutter config --enable-linux-desktop
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --fix-missing \
        clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev \
        libfuse2 keybinder-3.0 squashfs-tools python3-pip
    - name: Build flutter app
      run: flutter build linux
    - name: Build AppImage (x86_64)
      if: matrix.ARCH == 'x86_64'
      uses: docker://appimagecrafters/appimage-builder:1.1.0
      with:
        entrypoint: appimage-builder
        args: --recipe ./AppImageBuilder.yml --skip-test
    - name: Build AppImage (ARM)
      if: matrix.ARCH == 'armhf'
      run: |
        pip3 install appimage-builder
        appimage-builder --recipe ./AppImageBuilder.yml --skip-test
    - name: Save build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AppImage-${{ matrix.ARCH }}
        path: './*.AppImage*'
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Continuous build
        automatic_release_tag: '2.0.0'
        prerelease: false
        draft: true
        files: './*.AppImage*'
        repo_token: ${{ secrets.GITHUB_TOKEN }}
